<?php

namespace AppBundle\Repository;

/**
 * ComplementarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplementarioRepository extends \Doctrine\ORM\EntityRepository
{
}
