<?php

namespace AppBundle\Repository;

/**
 * DoctorUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctorUserRepository extends \Doctrine\ORM\EntityRepository
{
}