<?php

namespace AppBundle\Repository;

/**
 * EstudianteUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudianteUserRepository extends \Doctrine\ORM\EntityRepository
{
}