<?php

namespace AppBundle\Repository;

/**
 * HojaEnfermeriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HojaEnfermeriaRepository extends \Doctrine\ORM\EntityRepository
{
}
