<?php

namespace AppBundle\Repository;

/**
 * IngresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngresoRepository extends \Doctrine\ORM\EntityRepository
{
}
