<?php

namespace AppBundle\Repository;

/**
 * LaboratorioUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratorioUserRepository extends \Doctrine\ORM\EntityRepository
{
}