<?php

namespace AppBundle\Repository;

/**
 * PacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteRepository extends \Doctrine\ORM\EntityRepository
{
}
