services:
  app.admin.post:
    class: AppBundle\Admin\DoctorAdmin
    tags:
        - { name: sonata.admin, manager_type: orm, group: "Content", label: "Doctor" }
    arguments:
        - ~
        - AppBundle\Entity\Doctor
        - ~
    calls:
        - [ setTranslationDomain, [AppBundle]]