imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }
    - { resource: "@APIBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    genders:
        m: Male
        f: Female

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'form/fields.html.twig'
#    form:
#        resources:
#            - LexikFormFilterBundle:Form:form_div_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        # Uncomment next line:
        path:     "%kernel.root_dir%/data.db3"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS UserBundle Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    service:
        user_manager: pugx_user_manager

#twig:
#    form:
#        resources:
#            - LexikFormFilterBundle:Form:form_div_layout.html.twig

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        # ...

pugx_multi_user:
  users:
    doctor:
        entity:
          class: AppBundle\Entity\DoctorUser
#          factory:
#        registration:
#          form:
#            type: AppBundle\Form\DoctorUserRegistrationType
#            name: fos_user_registration_form
#            validation_groups:  [Registration, Default]
#          template: AppBundle:Registration:doctor.form.html.twig
        profile:
          form:
            type: AppBundle\Form\DoctorUserProfileType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
    admin:
        entity:
          class: AppBundle\Entity\AdminUser
#        registration:
#          form:
#            type: AppBundle\Form\AdminUserRegistrationType
#            name: fos_user_registration_form
#            validation_groups:  [Registration, Default]
#          template: AppBundle:Registration:admin.form.html.twig
        profile:
          form:
            type: AppBundle\Form\AdminUserProfileType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
    laboratorio:
        entity:
          class: AppBundle\Entity\LaboratorioUser
#        registration:
#          form:
#            type: AppBundle\Form\LaboratorioUserRegistrationType
#            name: fos_user_registration_form
#            validation_groups:  [Registration, Default]
#          template: AppBundle:Registration:laboratorio.form.html.twig
        profile:
          form:
            type: AppBundle\Form\LaboratorioUserProfileType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
    estudiante:
        entity:
          class: AppBundle\Entity\EstudianteUser
#        registration:
#          form:
#            type: AppBundle\Form\EstudianteUserRegistrationType
#            name: fos_user_registration_form
#            validation_groups:  [Registration, Default]
#          template: AppBundle:Registration:estudiante.form.html.twig
        profile:
          form:
            type: AppBundle\Form\EstudianteUserProfileType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
    enfermero:
        entity:
          class: AppBundle\Entity\EnfermeroUser
#        registration:
#          form:
#            type: AppBundle\Form\EnfermeroUserRegistrationType
#            name: fos_user_registration_form
#            validation_groups:  [Registration, Default]
#          template: AppBundle:Registration:enfermero.form.html.twig
        profile:
          form:
            type: AppBundle\Form\EnfermeroUserProfileType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]
    residente:
        entity:
          class: AppBundle\Entity\ResidenteUser
#        registration:
#          form:
#            type: AppBundle\Form\ResidenteUserRegistrationType
#            name: fos_user_registration_form
#            validation_groups:  [Registration, Default]
#          template: AppBundle:Registration:residente.form.html.twig
        profile:
          form:
            type: AppBundle\Form\ResidenteUserProfileType
            name: fos_user_profile_form
            validation_groups:  [Profile, Default]