backend_user:
    resource: "@BackendBundle/Controller/UserController.php"
    type:     annotation

api:
    resource: "@APIBundle/Controller/"
    type:     annotation
    prefix:   /api

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"