<?php

namespace BackendBundle\Repository;

/**
 * ConsultasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaRepository extends \Doctrine\ORM\EntityRepository
{
}
