<?php

namespace BackendBundle\Repository;

/**
 * EnfermeroUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfermeroUserRepository extends \Doctrine\ORM\EntityRepository
{
}