<?php

namespace BackendBundle\Repository;

/**
 * HojaEnfermeria2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HojaEnfermeria2Repository extends \Doctrine\ORM\EntityRepository
{
}
