<?php

namespace BackendBundle\Repository;

/**
 * HojaMedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HojaMedicoRepository extends \Doctrine\ORM\EntityRepository
{
}
