<?php

namespace BackendBundle\Repository;

/**
 * IngresoSalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngresoSalaRepository extends \Doctrine\ORM\EntityRepository
{
}
