<?php

namespace BackendBundle\Repository;

/**
 * ResidenteUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResidenteUserRepository extends \Doctrine\ORM\EntityRepository
{
}