<?php

namespace BackendBundle\Repository;

/**
 * SexoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SexoRepository extends \Doctrine\ORM\EntityRepository
{
}
